spring:
  application:
    name: resource-user

server:
  port: 8083
  #contextPath: /users
  ssl:
    enabled: false
    keyAlias: ubwebapi
    keyPassword: Charter817
    keyStore: C:/certs/ssl-cert.jks 
    keyStoreProvider: SUN 
    keyStoreType: JKS    
        
security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        # Tells the JWT framework to fetch the public key from the authorization server during startup
        # Note: The authorization server needs to be running...
        #keyValue: "123"
        keyUri: "https://directsales-ub-local.ncw.webapps.rr.com:8081/oauth/token_key"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://directsales-ub-local.ncw.webapps.rr.com:8082/ecomm/eureka}

logging:
  level:
    org:
      springframework:
        security: INFO